server:
  port: ${PORT:8080}

spring:
  application:
    name: cognispace-api
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
          cache-public: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  registration:
    notify-to: ${APP_REGISTRATION_NOTIFY_TO:admin@stage.dev}
    mail-from: ${APP_REGISTRATION_MAIL_FROM:admin@stage.dev}
